version: '3'

services:
  redis:
    image: redis:latest
    container_name: bullmq-redis
    ports:
      - 46379:6379
    volumes:
      - ./docker/redis/data:/data
      - ./docker/redis/conf/redis.conf:/usr/local/conf/redis.conf
    restart: always
    command: redis-server /usr/local/conf/redis.conf
